export default {
	html5: "HTML5",
	figma: "Figma",
	react: "React",
	vue: "Vue",
	angular: "Angular",
	redux: "Redux",
	reactRouter: "React Router",
	vuex: "Vuex",
	vuesax: "Vuesax",
	php: "PHP",
	openServer: "Open Server",
	javaScript: "JavaScript",
	typeScript: "TypeScript",
	jquery: "JQuery",
	mysql: "MySQL",
	laravel: "Laravel",
	tailwind: "Tailwind CSS",
	scss: "SCSS",
	mvc: "MVC",
	nextjs: "NextJS",
	bootstrap: "Bootstrap",
	axios: "Axios",
	phpmyadmin: "PHPMyAdmin",
	ajax: "AJAX",
	restApi: "REST Api",
	sequelize: "Sequelize",
	vite: "Vite",
	nodejs: "NodeJS",
	postgresql: "PostgreSQL",
	spline: "Spline",
	vercel: "Vercel",
	vitest: "Vitest",
	prismaORM: "PrismaORM",
	zustand: "Zustand",
	behance: "Behance",
	dribble: "Dribble",
	uiKit: "UI Kit",
	atomicDesign: "Atomic Design",
	figmaStyles: "Figma Styles",
	responsiveDesign: "Responsive Design",
	userFlow: "User Flow",
	figmaComponents: "Figma Components",
	figmaPrototyping: "Figma Prototyping",
};
